name: Publisere Storybook til Github Pages
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Sjekke ut
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Installere PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Sette opp Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Installere avhengigheter
        run: pnpm install
      - name: Bygge Storybook
        run: pnpm run build-storybook
      - name: Laste opp Pages-artifakt
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'packages/web/storybook-static'
      - id: deploy
        name: Rulle ut til Github Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}