name: report-coverage.yml
on:
  workflow_run:
    workflows: ["Kjøre tester"]
    types: [completed]
  pull_request:
    types: [opened, synchronize]
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Sleep for 180 seconds
        run: sleep 180s
        shell: bash
      - uses: actions/checkout@v4
      - name: Testdekning Web
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./packages/web/coverage/coverage-summary.json
          json-final-path: ./packages/web/coverage/coverage-final.json
      - name: Testdekning React
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./packages/react/coverage/coverage-summary.json
          json-final-path: ./packages/react/coverage/coverage-final.json
