name: Kjøre tester

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Bygg og test
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble

    steps:
      - name: Sjekke ut kodelager
        uses: actions/checkout@v4

      - name: Installere PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Installere Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Installere avhengigheter
        run: pnpm install --frozen-lockfile

      - name: Kodestil
        run: pnpm codestyle

      - name: Bygge
        run: pnpm run build

      - name: Kodesjekk
        run: pnpm lint

      - name: Installere Playwright
        run: pnpm --filter tomas-designsystem --filter tomas-designsystem-react exec playwright install --with-deps

      - name: Test
        run: pnpm run test
